# 4/0

# y=test

# try:
#     print(x)
# except:
#     print("an exception has occurewd in the program")

